learningSalesforce/force-app/main/default/objects/Event_Registrations__c/Event_Registrations__c.object-meta.xml
<CustomObject>
    <description>Event Registrations.</description>
    <label>Event Registrations</label>
    <nameField>
        <label>Event Registrations. Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations.</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

learningSalesforce/force-app/main/default/objects/Event_Registrations__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Master-Details with Event Object</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations.</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

learningSalesforce/force-app/main/default/classes/EventRegistrationTriggerHandler.cls
public class EventRegistrationTriggerHandler {
	public static void updateEventRegisCounts(List<Event_Registrations__c>eventRegList){
		Map<Id,Decimal>eventMap=new Map<Id,Decimal>();
        for(Event_Registrations__c event:eventRegList){
            if(event.Event__c!=null){
                Decimal total=1;
                if(eventMap.containsKey(event.Event__c)){
                    total=eventMap.get(event.Event__c);
                }
                eventMap.put(event.Event__c,total);
            }
        }
        if(!eventMap.isEmpty()){
            List<Event__c>eventList=new List<event__c>();
            for(Event__c event:[Select Id from Event__c where Id=:eventMap.KeySet()]){
                eventList.add(new Event__c(Id=event.id,Total_Event_Registrations__c=eventMap.get(event.Id)));
            }
            update eventList;
        }
    }
}