learningSalesforce/force-app/main/default/objects/Event_Registrations__c/Event_Registrations__c.object-meta.xml
<CustomObject>
    <description>Event Registrations.</description>
    <label>Event Registrations</label>
    <nameField>
        <label>Event Registrations. Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations.</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

learningSalesforce/force-app/main/default/objects/Event_Registrations__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Master-Details with Event Object</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations.</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

learningSalesforce/force-app/main/default/classes/EventTriggerHandler.cls
public class EventTriggerHandler {
    public static void isBeforeInsert(List<Event__c>eventList){
        for(Event__c event:eventList){
            event.Event_Status__c='Planned';
        }
    }
    public static void updateEventRegisCounts(List<Event__c>eventList){
        Set<Id>eventIds=new Set<ID>();
        for(Event__c event:eventList){
            eventIds.add(event.id);
        }
        if(!eventIDs.isEmpty()){
            for(Event__c event:[Select Id,Total_Event_Registrations__c,(Select Id from Event_Registrations__r) from Event__c where Id=:eventIDs]){
                event.Total_Event_Registrations__c=event.Event_Registrations__r.size();
            }
        }
    }
}