learningSalesforce/force-app/main/default/objects/Event__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup with Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

learningSalesforce/force-app/main/default/objects/Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>Event Date</description>
    <label>Event Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

learningSalesforce/force-app/main/default/objects/Event__c/fields/Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Event_Location__c</fullName>
    <description>Event Location</description>
    <label>Event Location</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

learningSalesforce/force-app/main/default/classes/DMLOperations.cls
public class DMLOperations {
    public static void insertAccount(){
        try{
            Account acc=new Account(Name='AmanTest13Sep');
            insert acc;
            Event__c event=new Event__c(Name='EV13Sept',Event_Date__c=System.today(),Event_Location__c='Location 1',Account__c=acc.id);
            insert event;
        }catch(DMLException e){
            System.debug(e.getMessage());
        }
    }
    public static void updateAccount(){
        try{
            /*List<Account>accList=[Select Id from Account where Name='AnkitTest13Sep'];
            for(Account acc:accList){
                acc.Name='AnkitTest13Sep';
            }
            update accList;*/
            List<Event__c>eventList=[Select Id from Event__c where Name='EV13Sept'];
            for(Event__c event:eventList){
                event.Event_Location__c='Location 13 Sep';
            }
            update eventList;
        }catch(DMLException e){
            System.debug(e.getMessage());
        }

    }
    public static void upsertAccont(){
        try{
            List<Event__c>eventList=new List<Event__c>();
            Account acc=[Select Id from Account where name='AmanTest13Sep'];
            Event__c event1=[Select Id from Event__c where Name='EV13Sept'];
            event1.Name='Ev13Sept1';
            Event__c event=new Event__c(Name='EV13Sept2',Event_Date__c=System.today(),Event_Location__c='Location 1',Account__c=acc.id);
            eventList.add(event1);
            eventList.add(event);
            upsert eventList;
        }catch(DMLException e){
            System.debug(e.getMessage());
        }
    }
    public static void deleteAccount(){
        try{
            List<Event__c>eventList=[Select Id from Event__c where createdDate=today];
            delete eventList;
        }catch(DMLException e){
            System.debug(e.getMessage());
        }
    }
    public static void undeleteAccount(){
        try{
            List<Event__c>eventList=[Select Id from Event__c where createdDate=today All Rows];
            undelete eventList;
        }catch(DMLException e){
            System.debug(e.getMessage());
        }
    }
}